version: '3.8'
services:
  auth-service:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=auth_db
      - PORT=3000
      - ENV=development
      - JWT_SECRET=JWT_SECRET
      - JWT_REFRESH_SECRET=JWT_REFRESH_SECRET
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - JWT_ACCESS_TOKEN_EXPIRES_IN=300
      - JWT_REFRESH_TOKEN_EXPIRES_IN=3600
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: